rules:
  indent:
    - 0
    - 4
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  no-fallthrough:
    - 0
env:
  browser: true
extends: 'eslint:recommended'
